core/urls.py
from django.urls import path

from .views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

despesa/urls.py
from django.urls import include, path
from rest_framework import routers

from despesa.api.viewsets import DespesaViewSet, DespesaAutenticationView

app_name = 'despesa'

router = routers.DefaultRouter()

router.register(r'despesas', DespesaViewSet, basename='despesas')

from . import views

urlpatterns = [
    path('ptrab/', views.despesa_list, name='despesa_list'),
    #path('create/', v.despesa_create, name='despesa_create'),
    path('api/v1/', include(router.urls)),
    path('api/v1/despesa-autentication/', DespesaAutenticationView.as_view())
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def index(request):
    template_name = 'index.html'
    return render(request, template_name)

core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-light bg-success fixed-top fs-5">
  <a class="navbar-brand" href="{% url 'core:index' %}"><img src="http://www.coter.eb.mil.br/images/sistema/icones/logo/02_logo_normal_g.png" class="img-fluid w-50 p-0"> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">SIOF<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link fw-bold" href="http://www.coter.eb.mil.br/" target="_blank">COTER</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://www.coter.eb.mil.br/index.php/2-subchefia" target="_blank">Chefia do Emp F Ter</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          API V1
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/api/v1/documentos/">Documentos</a>
          <a class="dropdown-item" href="/api/v1/tipoptrab/">Tipo PTrab</a>
          <a class="dropdown-item" href="/api/v1/ptrab/">PTrab</a>
          <a class="dropdown-item" href="/api/v1/tipodespesa/">Tipo Despesas</a>
          <a class="dropdown-item" href="/api/v1/despesas/">Despesas</a>
          <a class="dropdown-item" href="/api/v1/cmdomilarea/">Cmdo Mil A</a>
          <a class="dropdown-item" href="/api/v1/regiaomilitar/">Regiões Militares</a>
          <a class="dropdown-item" href="/api/v1/unidades/">Unidades</a>
          <a class="dropdown-item" href="/api/v1/estados/">Estados</a>
          <a class="dropdown-item" href="/api/v1/cidades/">Cidades</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/swagger/">Documentação API</a>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'despesa:despesa_list' %}">PTrab</a>
      </li>
  
      <li class="nav-item">
        <a class="nav-link" href="{ url 'core:sobre' %}">Sobre</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{ url 'core:contatos' %}">Contatos</a>
      </li>

    </ul>
  </div>
</nav>